# Generated by Django 4.1.5 on 2023-01-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('joining_date', models.DateField()),
                ('sales_count', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=255)),
            ],
        ),
    ]
