# Generated by Django 4.1.5 on 2023-01-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
