# Generated by Django 4.1.5 on 2023-01-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0005_alter_user_address_alter_user_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Title', models.TextField()),
                ('Product_Description', models.TextField(blank=True)),
                ('Product_Type', models.CharField(default='simple', max_length=255)),
                ('Product_Image', models.TextField(blank=True)),
                ('Product_SKU', models.CharField(blank=True, max_length=255)),
                ('Tags', models.TextField(blank=True)),
                ('Stock', models.IntegerField(default=1)),
                ('Price', models.FloatField()),
                ('Cat_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categor1y_ID', to='CSE.category')),
                ('Parent_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE.product')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_11ID', to='CSE.user')),
            ],
        ),
    ]
