# Generated by Django 4.1.5 on 2023-01-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Store_Name', models.TextField()),
                ('Store_Location', models.TextField()),
                ('Managers', models.TextField()),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product111_ID', to='CSE.product')),
            ],
        ),
    ]
