# Generated by Django 4.1.5 on 2023-01-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0008_alter_product_cat_id_alter_product_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=255)),
                ('Customer_Phone', models.CharField(max_length=15)),
                ('Customer_Email', models.EmailField(blank=True, max_length=254)),
                ('Delivery_Address', models.TextField(blank=True)),
                ('Is_Self_Delivery', models.BooleanField(default=False)),
                ('Is_online_Payment', models.BooleanField(default=False)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Delivery_Charge', models.FloatField(default=0.0)),
                ('Discount', models.FloatField(default=0.0)),
                ('Product_Total_Price', models.FloatField(default=0.0)),
                ('Remarks', models.TextField(blank=True)),
                ('Payment_Status', models.TextField(default='Unpaid')),
                ('Invoice_Status', models.TextField(default='Initial')),
                ('Delivery_Boy_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Delivery_Boy_ID', to='CSE.user')),
                ('Sales_Manger_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sales_Manager_ID', to='CSE.user')),
                ('Store_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSE.store')),
                ('Store_Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Store_Manager_ID', to='CSE.user')),
            ],
        ),
    ]
