# Generated by Django 4.1.5 on 2023-01-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0011_notification_invoice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Delivery_Boy_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivery_Boy_ID', to='CSE.user'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Discount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Product_Total_Price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Store_Manager_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store_Manager_ID', to='CSE.user'),
        ),
    ]
