# Generated by Django 4.1.5 on 2023-01-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0012_alter_invoice_delivery_boy_id_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Store_ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CSE.store'),
        ),
    ]
