# Generated by Django 4.1.5 on 2023-01-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0014_alter_category_parent_id_alter_product_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Parent_ID',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSE.category'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Delivery_Boy_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivery_Boy_ID', to='CSE.user'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Store_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSE.store'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Store_Manager_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store_Manager_ID', to='CSE.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Parent_ID',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSE.product'),
        ),
    ]
