# Generated by Django 4.1.5 on 2023-01-05 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0017_alter_product_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Parent_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSE.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Parent_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CSE.product'),
        ),
    ]
